#:import get_color_from_hex kivy.utils.get_color_from_hex

MDScreen:
    md_bg_color: 0, 0, 0, 1

    # Círculo Neon de Fundo (Pintado na GPU)
    Widget:
        canvas:
            Color:
                rgba: get_color_from_hex('#39FF14')
            Line:
                circle: (self.center_x, self.center_y + dp(100), dp(85))
                width: dp(1.8)
            Color:
                rgba: 0.22, 1, 0.08, 0.15
            Line:
                circle: (self.center_x, self.center_y + dp(100), dp(95))
                width: dp(4)

    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(25)
        spacing: dp(12)

        MDLabel:
            text: "SUPREMEFLY REGEDIT V4"
            halign: "center"
            font_style: "H4"
            bold: True
            theme_text_color: "Custom"
            text_color: get_color_from_hex('#39FF14')
            size_hint_y: None
            height: dp(80)

        Widget:
            size_hint_y: None
            height: dp(180) # Espaço para o círculo aparecer

        MDLabel:
            text: "SENSIBILIDADE X / Y"
            theme_text_color: "Secondary"
            font_style: "Caption"
            halign: "center"

        MDSlider:
            id: sensi_x
            min: 0
            max: 1000
            value: 650
            color: get_color_from_hex('#39FF14')

        MDSlider:
            id: sensi_y
            min: 0
            max: 1000
            value: 800
            color: get_color_from_hex('#39FF14')

        MDFillRoundFlatButton:
            text: "EXECUTAR NO HARDWARE"
            size_hint_x: 1
            md_bg_color: get_color_from_hex('#39FF14')
            text_color: 0, 0, 0, 1
            font_style: "Button"
            on_release: app.apply_hardware_logic()

        MDLabel:
            id: log_label
            text: "> SISTEMA AGUARDANDO COMANDO"
            halign: "center"
            theme_text_color: "Custom"
            text_color: get_color_from_hex('#39FF14')
            font_style: "Caption"
