name: Gerar APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet
        run: pip install flet

      - name: Forçar Criação do Projeto e Build
        run: |
          # Isso cria os arquivos que o Android precisa
          flet create . --template app --force
          # Isso constrói o APK ignorando avisos bobos
          flet build apk --verbose

      - name: Enviar APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: App-Supreme-Instalador
          path: build/apk/*.apk
