name: Gerar APK Supremo
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias
        run: |
          pip install flet
          flet sdk install

      - name: Compilar APK
        run: |
          flet build apk

      - name: Upload do APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SupremeTouch-Instalador
          path: build/apk/*.apk
